### ISSUE TITLE
New Delete Button util function

### ISSUE THREAD

**Issue by crudobaker** [crudobaker/chebot#28]
Implement an util function to create a Delete Button.

Currently we are doing:
```
newActionButton('Eliminar ❌', actionName, ...actionParams)
```

We need to move to something like:
```
newDeleteButton(actionName, ...actionParams)
```

**Comment by pablotocalini** [comment]
inside keyboar-utils y wrote this function
´´´
// function for delete button
export function newDeleteButton(actionName, ...actionParams) {
  return newActionButton('Eliminar ❌', actionName, ...actionParams)
}
´´´
